services:
    message-broker:
        image: rabbitmq:3-management-alpine
        container_name: message-broker
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - rabbitmq_log:/var/log/rabbitmq
        networks:
            - message-broker-networks
    you-shop-database:
        image: postgres:17.2-alpine3.21
        container_name: you-shop-database
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
    you-shop-product-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
    you-shop-product-api-dev:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
volumes:
    rabbitmq_data:
    rabbitmq_log:
networks:
    message-broker-networks:
        driver: bridge
